<?php
session_start();
require_once '../auth/conn.php'; 

if (!isset($_SESSION['user_id']) || $_SESSION['role'] !== 'admin') {
    exit("Access Denied");
}

$format = $_GET['format'] ?? 'csv';
$filename = "Sales_Report_" . date('Y-m-d');

try {
    // Fetch Order Data
    $stmt = $pdo->query("SELECT o.*, p.product_name 
                         FROM orders o 
                         JOIN products p ON o.product_id = p.id 
                         WHERE o.status = 'Approved' 
                         ORDER BY o.created_at DESC");
    $data = $stmt->fetchAll(PDO::FETCH_ASSOC);

    if ($format === 'excel' || $format === 'csv') {
        ob_end_clean();
        header('Content-Type: text/csv; charset=utf-8');
        header('Content-Disposition: attachment; filename='.$filename.'.csv');
        
        $output = fopen('php://output', 'w');
        fputcsv($output, ['Order ID', 'Customer', 'Product', 'Qty', 'Total Price', 'Status', 'Date']);
        
        foreach ($data as $row) {
            fputcsv($output, [
                $row['id'] ?? $row['order_id'] ?? 'N/A',
                $row['customer_name'] ?? 'Walk-in',
                $row['product_name'],
                $row['qty'] ?? 1,
                "₱" . number_format($row['total_price'], 2),
                $row['status'],
                $row['created_at']
            ]);
        }
        fclose($output);
        exit();

    } elseif ($format === 'pdf') {
        ?>
        <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <title>Official Sales Report - <?= date('Y-m-d') ?></title>
            <style>
                body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; padding: 40px; color: #333; }
                .report-header { display: flex; justify-content: space-between; align-items: center; border-bottom: 2px solid #f28c28; padding-bottom: 10px; margin-bottom: 30px; }
                table { width: 100%; border-collapse: collapse; }
                th { background-color: #f28c28; color: white; padding: 12px; text-align: left; }
                td { padding: 12px; border-bottom: 1px solid #eee; }
                .total-row { font-weight: bold; background: #f9f9f9; }
                @media print { .no-print { display: none; } }
            </style>
        </head>
        <body>
            <div class="no-print" style="margin-bottom: 20px;">
                <button onclick="window.print()" style="padding: 10px 20px; background: #27ae60; color: white; border: none; cursor: pointer; border-radius: 5px; font-weight: bold;">
                    Click to Print or Save as PDF
                </button>
            </div>
            <div class="report-header">
                <div>
                    <h1 style="margin:0; color:#f28c28;">Sales Report</h1>
                    <p style="margin:5px 0;">Official Management Document</p>
                </div>
                <div style="text-align: right;">
                    <p><strong>Date:</strong> <?= date('F j, Y') ?></p>
                    <p><strong>Time:</strong> <?= date('g:i a') ?></p>
                </div>
            </div>
            <table>
                <thead>
                    <tr>
                        <th>Order ID</th>
                        <th>Customer</th>
                        <th>Product</th>
                        <th>Qty</th>
                        <th>Total Amount</th>
                        <th>Date</th>
                    </tr>
                </thead>
                <tbody>
                    <?php 
                    $grandTotal = 0;
                    foreach ($data as $row): 
                        $grandTotal += $row['total_price'];
                    ?>
                    <tr>
                        <td>#<?= $row['id'] ?? $row['order_id'] ?></td>
                        <td><?= htmlspecialchars($row['customer_name'] ?? 'Walk-in') ?></td>
                        <td><?= htmlspecialchars($row['product_name']) ?></td>
                        <td><?= $row['qty'] ?? 1 ?></td>
                        <td>₱<?= number_format($row['total_price'], 2) ?></td>
                        <td><?= date('Y-m-d', strtotime($row['created_at'])) ?></td>
                    </tr>
                    <?php endforeach; ?>
                    <tr class="total-row">
                        <td colspan="4" style="text-align: right;">Grand Total:</td>
                        <td colspan="2">₱<?= number_format($grandTotal, 2) ?></td>
                    </tr>
                </tbody>
            </table>
            <div style="margin-top: 50px; font-size: 0.8rem; color: #7f8c8d; text-align: center;">
                <p>Generated by Admin Management System. This is a computer-generated report.</p>
            </div>
        </body>
        </html>
        <?php
        exit();
    }
} catch (PDOException $e) {
    die("Export Error: " . $e->getMessage());
}
?>